### PR TITLE
Implement fire_event function

### PR DESCRIPTION
**Pull request by a-nigredo**

### CODE REVIEW

**Comment by pravic** [comment]
Great. I'll look on it.

But its better to create separate example for the native events playground.

**Comment by a-nigredo** [comment]
Do you mean that I should add examples for fire event as a separate file?

**Comment by pravic** [comment]
Exactly.

**Comment by a-nigredo** [comment]
Ok, I'll add as soon as I get an answer to [http://sciter.com/forums/topic/fire-event-and-data/](url). Since I don't understand why fired event can be caught by handler which is attached to main window only.

**Comment by pravic** [comment]
Going to look this weekend. Sorry for delay :)

**Comment by pravic** [comment]
Did it myself today.

**Pull request closed without merging**
